server:
  port: 8082

spring:
  application:
    name: users-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users_db}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:18.188.55.33:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:users-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.cinema.users_service.messaging.UserCreatedEvent

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

users:
  kafka:
    topic-user-events: user-events

